# Generated by Django 5.0.1 on 2024-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheitem',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cachejob',
            name='time_frame',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=10),
        ),
    ]
